name: Check for infrastructure drift on Management

on:
  schedule:
    - cron: 0 8 * * *

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of MPE Transport terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        uses: azurenoops/terraform-github-actions/terraform-check@v1.34.2
        with:
          path: src
          variables: |
            subscription_id_hub               = "${{ env.ARM_SUBSCRIPTION_ID }}"
            subscription_id_sandbox           = "${{ secrets.AZURE_SANDBOX_SUBSCRIPTION_ID }}"
            subscription_id_internal          = "${{ secrets.AZURE_INTERNAL_SUBSCRIPTION_ID }}"
            subscription_id_partners_gsa_dev  = "${{ secrets.AZURE_PARTNER_GSA_DEV_SUBSCRIPTION_ID }}"
            subscription_id_partners_gsa_prod = "${{ secrets.AZURE_PARTNER_GSA_PROD_SUBSCRIPTION_ID }}"
          var_file: |
            src/tfvars/production/deploy.prod.tfvars

      - name: Changes detected
        if: ${{ failure() && steps.check.outputs.failure-reason == 'changes-to-apply' }}
        run: echo "There are outstanding terraform changes to apply"